### ISSUE TITLE
Warning and Error after a little while running the code, Yasmin module related

### ISSUE THREAD

**Issue by Power2All** [CharlotteDunois/Yasmin#83] opened 2019-02-16 15:41 UTC
**Please describe the issue you are having:**
Console log shows errors, that hasn't got anything to do with my custom code.
Warning and a Fatal error.

**If you are encountering any errors, post the full stack trace here:**
```
PHP Warning:  Illegal string offset 'id' in /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/GuildMemberStorage.php on line 104
PHP Warning:  Illegal string offset 'id' in /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php on line 122
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CharlotteDunois\Yasmin\Models\UserStorage::patch() must be of the type array, string given, called in /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php on line 123 and defined in /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/UserStorage.php:67
Stack trace:
#0 /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php(123): CharlotteDunois\Yasmin\Models\UserStorage->patch('237268160397574...')
#1 /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/GuildMemberStorage.php(110): CharlotteDunois\Yasmin\Models\GuildMember->__construct(Object(CharlotteDunois\Livia\LiviaClient), Object(CharlotteDunois\Yasmin\Models\Guild), Array)
#2 /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/Guild.php(1200): CharlotteDunois\Yasmin\Models\GuildMemberStorage->factory(Array)
#3 /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/WebSocket/Events/TypingStart.php(42): CharlotteDunois\Yasmin\Mo in /mnt/d/git/wow_discord/vendor/charlottedunois/yasmin/src/Models/UserStorage.php on line 67
```

**Please include a Minimal, Complete and Verifiable Example:**
There is non, since it's not affecting my custom code, it happens when traffic is being handled by your module, and it won't hit my cuistom code.

**Please include the expected output of the MCVE:**
Should not give any errors or warnings whatsoever.

**Please include the actual output of the MCVE:**
None..

**Further details:**

- Yasmin version: v0.5.1
- PHP version: 7.2.10-0ubuntu0.18.04.1
- Operating System: Ubuntu 18.04

**Comment by CharlotteDunois** [comment] 2019-02-16 15:46
Duplicate of #79

**Closed by CharlotteDunois** 2019-02-16 15:46 UTC
